/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthenticatedNcaaChecklistRouteImport } from './routes/_authenticated/ncaa-checklist'
import { Route as AuthenticatedParentViewRouteImport } from './routes/_authenticated/parent-view'
import { Route as AuthenticatedScoutProfileRouteImport } from './routes/_authenticated/scout-profile'
import { Route as AuthenticatedTrainingDashboardRouteImport } from './routes/_authenticated/training-dashboard'
import { Route as AuthenticatedTrainingPlanRouteImport } from './routes/_authenticated/training-plan'
import { Route as ApiTrainingPlanRouteImport } from './routes/api/training-plan'
import { Route as PSlugRouteImport } from './routes/p.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNcaaChecklistRoute =
  AuthenticatedNcaaChecklistRouteImport.update({
    id: '/ncaa-checklist',
    path: '/ncaa-checklist',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedParentViewRoute = AuthenticatedParentViewRouteImport.update({
  id: '/parent-view',
  path: '/parent-view',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScoutProfileRoute =
  AuthenticatedScoutProfileRouteImport.update({
    id: '/scout-profile',
    path: '/scout-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingDashboardRoute =
  AuthenticatedTrainingDashboardRouteImport.update({
    id: '/training-dashboard',
    path: '/training-dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTrainingPlanRoute =
  AuthenticatedTrainingPlanRouteImport.update({
    id: '/training-plan',
    path: '/training-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiTrainingPlanRoute = ApiTrainingPlanRouteImport.update({
  id: '/api/training-plan',
  path: '/api/training-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/ncaa-checklist': typeof AuthenticatedNcaaChecklistRoute
  '/parent-view': typeof AuthenticatedParentViewRoute
  '/scout-profile': typeof AuthenticatedScoutProfileRoute
  '/training-dashboard': typeof AuthenticatedTrainingDashboardRoute
  '/training-plan': typeof AuthenticatedTrainingPlanRoute
  '/api/training-plan': typeof ApiTrainingPlanRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/ncaa-checklist': typeof AuthenticatedNcaaChecklistRoute
  '/parent-view': typeof AuthenticatedParentViewRoute
  '/scout-profile': typeof AuthenticatedScoutProfileRoute
  '/training-dashboard': typeof AuthenticatedTrainingDashboardRoute
  '/training-plan': typeof AuthenticatedTrainingPlanRoute
  '/api/training-plan': typeof ApiTrainingPlanRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/_authenticated/ncaa-checklist': typeof AuthenticatedNcaaChecklistRoute
  '/_authenticated/parent-view': typeof AuthenticatedParentViewRoute
  '/_authenticated/scout-profile': typeof AuthenticatedScoutProfileRoute
  '/_authenticated/training-dashboard': typeof AuthenticatedTrainingDashboardRoute
  '/_authenticated/training-plan': typeof AuthenticatedTrainingPlanRoute
  '/api/training-plan': typeof ApiTrainingPlanRoute
  '/p/$slug': typeof PSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/ncaa-checklist'
    | '/parent-view'
    | '/scout-profile'
    | '/training-dashboard'
    | '/training-plan'
    | '/api/training-plan'
    | '/p/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/ncaa-checklist'
    | '/parent-view'
    | '/scout-profile'
    | '/training-dashboard'
    | '/training-plan'
    | '/api/training-plan'
    | '/p/$slug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/dashboard'
    | '/_authenticated/ncaa-checklist'
    | '/_authenticated/parent-view'
    | '/_authenticated/scout-profile'
    | '/_authenticated/training-dashboard'
    | '/_authenticated/training-plan'
    | '/api/training-plan'
    | '/p/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  ApiTrainingPlanRoute: typeof ApiTrainingPlanRoute
  PSlugRoute: typeof PSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ncaa-checklist': {
      id: '/_authenticated/ncaa-checklist'
      path: '/ncaa-checklist'
      fullPath: '/ncaa-checklist'
      preLoaderRoute: typeof AuthenticatedNcaaChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/parent-view': {
      id: '/_authenticated/parent-view'
      path: '/parent-view'
      fullPath: '/parent-view'
      preLoaderRoute: typeof AuthenticatedParentViewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scout-profile': {
      id: '/_authenticated/scout-profile'
      path: '/scout-profile'
      fullPath: '/scout-profile'
      preLoaderRoute: typeof AuthenticatedScoutProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training-dashboard': {
      id: '/_authenticated/training-dashboard'
      path: '/training-dashboard'
      fullPath: '/training-dashboard'
      preLoaderRoute: typeof AuthenticatedTrainingDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/training-plan': {
      id: '/_authenticated/training-plan'
      path: '/training-plan'
      fullPath: '/training-plan'
      preLoaderRoute: typeof AuthenticatedTrainingPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/training-plan': {
      id: '/api/training-plan'
      path: '/api/training-plan'
      fullPath: '/api/training-plan'
      preLoaderRoute: typeof ApiTrainingPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNcaaChecklistRoute: typeof AuthenticatedNcaaChecklistRoute
  AuthenticatedParentViewRoute: typeof AuthenticatedParentViewRoute
  AuthenticatedScoutProfileRoute: typeof AuthenticatedScoutProfileRoute
  AuthenticatedTrainingDashboardRoute: typeof AuthenticatedTrainingDashboardRoute
  AuthenticatedTrainingPlanRoute: typeof AuthenticatedTrainingPlanRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNcaaChecklistRoute: AuthenticatedNcaaChecklistRoute,
  AuthenticatedParentViewRoute: AuthenticatedParentViewRoute,
  AuthenticatedScoutProfileRoute: AuthenticatedScoutProfileRoute,
  AuthenticatedTrainingDashboardRoute: AuthenticatedTrainingDashboardRoute,
  AuthenticatedTrainingPlanRoute: AuthenticatedTrainingPlanRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  ApiTrainingPlanRoute: ApiTrainingPlanRoute,
  PSlugRoute: PSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
